### PR TITLE
Create US page

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

**Note**: This PR only contains some of the changes, as a lot of the work was pushed directly to main. Most of the project is copy&pasted from [cloud-init.io](https://github.com/canonical/cloud-init.io), where any reference to cloud-init.io has been changed to summit.ubuntu.com. So shouldn't need reviewing.
**Another note**: Ignore the `lint-scss` check, it is broken in the project and given the time sensitive and limited life span of the project, can be ignored.
- Creates page using content and UX decisions from the [copydoc](https://docs.google.com/document/d/1iS7IXts2jPAedBB8uar6SaU3qNizAZ7QeYdfb60VGuk/edit#) and the [brief](https://docs.google.com/document/d/1NbzODAqJQxbaArxfajjJODdi8CYPYD8CQ4vB-LRjr_o/edit#)

## QA

You will have to run the project locally in order to QA it as the staging environment has not been set up yet.

## Issue
Fixes https://github.com/canonical/master-epics/issues/446

### CODE REVIEW

**Review by sowasred2012 — CHANGES_REQUESTED** [review]
Couple of things I can't comment on the code:

- There's a div with a class of .page-content, this should be changed to a `main` element with an ID of `main-content` so that the skip link works (press Tab when the page loads and you'll see it, hit enter and it should jump the page past the global nav)
- The meta title and favicon have not changed since cloud-init.io, @davegoddard42 would new Ubuntu favicon be OK for this do you think?
- The Report A Bug link in the footer still links to cloud-init.io repo
- The footer has a HR right at the top, which looks odd right after a suru strip:
image

**Comment by davegoddard42** [comment]
@sowasred2012 @petesfrench - yep the new Ubuntu favicon (Circle of Friends) would be right for this page. 

I've spotted something else - the links in the "Want more information?" section are all the same - they have the same wording and all link to the same page. This is quite possibly my fault, when I was reformatting the page I may have done this. 

The links should follow the section on the copy doc at the very end:

image

**Comment by davegoddard42** [comment]
Also @petesfrench - sorry, cloud we change the titles of the Ubuntu, Discourse and Community to remove the h4 styling? I think they look better as h3.

**Comment by petesfrench** [comment]
Thank you @davegoddard42 and @sowasred2012, I have applied those changes if you want to have another look

**Review by sowasred2012 — CHANGES_REQUESTED** [review]
Couple more things:
- The meta title still hasn't changed, it reads " - The standard for customising cloud instances", which is from cloud-init.io
- The links in this section need their copy updating per @davegoddard42's comment, at the moment they all say the same thing, but link to different places:
image
- This email address should be a link, as it is further down the page:
image

**Review by sowasred2012 — APPROVED** [review]
LGTM

**Pull request merged**
